### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by BahtiyarDhani** [graker/oc-photoalbums-plugin#1]
Hello graker, is it possible to use pagination on your plugin? How to do that, if its possible? Pls give me a tutoruial.. Thanks

**Comment by BahtiyarDhani** [comment]
Also, is it possible to use custom tumbnail for each album?

**Comment by graker** [comment]
Hi @BahtiyarDhani , yes, pagination is supported for albums list component (to go through albums) and for album component (to go through photos). Amount of albums/photos on page is controlled by `albumsOnPage` and `photosOnPage` properties of albums list and album components. Just add component to a page, set property on the component and it should work out of the box. You can find pagination markup inside component partials in `graker/photoalbums/components/album/default.html` and `graker/photoalbums/components/albumlist/default.htm`.

Also there is mini-navigation in photo component to go to next/previous photo.

**Comment by graker** [comment]
> Also, is it possible to use custom tumbnail for each album?

Nope. At the moment, the last uploaded photo will be used as album thumbnail automatically. Photo reordering interface is on the way and in the [roadmap](https://github.com/graker/photoalbums#roadmap), but I can't tell right now when it will be available.

For now you can only "select" the thumbnail by uploading it after every other photo.

**Comment by graker** [comment]
In case you are interested, I've implemented a feature allowing to select any photo in the album to be it's front thumbnail. You can check it out by updating the code and running `php artisan october:up` to migrate the new `front` column in albums table.

**Comment by BahtiyarDhani** [comment]
Hi Graker,

Wow cool, thanks for updating your plugin.

Regards,
Dhani
