### ISSUE TITLE
Album pagination

### ISSUE THREAD

**Issue by karolkalkus** [graker/oc-photoalbums-plugin#10]
Hi Graker, 
I am using your plugin to show photos on page. In most I care about photos pagination.
Everything works fine but I have a little problem with pagination. 
I have got page `/albums/:slug` and on this page just added album component like this:

```
{% set album = photoAlbum.album %}

<h1>{{ album.title }}</h1>

{% if album.description %}
    <div class="album-description row">
        <div class="col-xs-12">
            {{ album.description|raw }}
        </div>
    </div>
{% endif %}

<div class="album-photos row">
    {% for photo in album.photos %}
        <div class="photo col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <a href="{{ photo.url }}"><img
                    data-src="{{ photo.thumb }}"
                    src="{{ photo.thumb }}"
                    alt="{{ photo.title }}"
                    title="{{ photo.title }}"
                    style="max-width: 100%" />
            </a>
            <a href="{{ photo.url }}"><strong>{{ photo.title }}</strong></a>
        </div>
    {% else %}
        <div class="col-xs-12 no-data">Album doesn't have any photos yet</div>
    {% endfor %}
</div>

{% if photoAlbum.lastPage > 1 %}
<ul class="pagination">
    {% if photoAlbum.currentPage > 1 %}
    <li><a href="{{ this.page.baseFileName|page }}?page={{ photoAlbum.currentPage-1 }}">&larr; Prev</a></li>
    {% endif %}

    {% for page in 1..photoAlbum.lastPage %}
    <li class="{{ photoAlbum.currentPage == page ? 'active' : null }}">
        <a href="{{ this.page.baseFileName|page }}?page={{ page }}">{{ page }}</a>
    </li>
    {% endfor %}

    {% if photoAlbum.lastPage > photoAlbum.currentPage %}
    <li><a href="{{ this.page.baseFileName|page }}?page={{ photoAlbum.currentPage+1 }}">Next &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
```

I set photos on page to be 8. In the fragment "menu" I added albumList component to display all galleries in the dropdown submenu.
```
<ul class="submenu">
    {% for album in albumList.albums %}
        <li>
            <a href="albums/{{album.slug}}">{{ album.title|raw }}</a>
        </li>
    {% endfor %}
</ul>
```
It works perfectly but when I goes e.g. to `/albums/myphotos?page=2`, dropdown submenu is empty. It doesn't work even when I use other plugin e.g. rainlab blog to display list of albums. When I goes to `/albums/myphotos?page=1` or just `/albums/myphotos` dropdown submenu shows albums.

The same situation when I want to add prev - next navigation in single album page.
```
{% set portfolios = albumList.albums %}
{% for portfolio in portfolios %}{% if this.param.slug == portfolio.slug %}
<div class="wrapper">
    <ul class="single-pagination">
        {% if not loop.first %}
        <li class="prev"><a href="{{'portfolio'|page}}/{{portfolios[loop.index0-1].slug}}"><img src="{{portfolios[loop.index0-1].latestPhoto.thumb}}" alt="prev"><span> {{portfolios[loop.index0-1].title}}</span></a></li>
        {% endif %}
        <li class="backtoworks"><a href="{{'portfolio'|page}}">Albums</a></li>
        {% if not loop.last %}
        <li class="next"><a href="{{'portfolio'|page}}/{{portfolios[loop.index0+1].slug}}"><img src="{{portfolios[loop.index0+1].latestPhoto.thumb}}" alt="next"><span> {{portfolios[loop.index0+1].title}}</span></a></li>
        {% endif %}
    </ul>
</div>
{% endif %}
{% endfor %}
```
When I add two components `Album` and `Album list` on the same page, photos pagination doesn't work. When I add partial to `/albums` page with above code, on `?page=2` prev - next navigation disappears, on `?page=1` or just `/albums/myphotos` its visible.

I don't know if it's a problem or I'm doing something wrong?

**Comment by graker** [comment]
Thanks Karol, I'll take a look.

**Comment by graker** [comment]
Sorry, forgot about this one totally.

It seems that the problem is that pagers for both of the components use the same internal id. So when you try to go to page 2 for your component that has content for page 2, your other component picks up the same pager parameter and tries to load page 2 as well. I didn't stumble into this particular situation in OctoberCMS so I can't post the quick solution here right away. But what I can tell is that in other platforms you usually have to provide different ids for different component pagers in situations like this. So the solution might be outside of the plugin code scope.

Though, if the solution does have something to do with the plugin code, feel free to reopen and we'll figure it out.
