### ISSUE TITLE
Radnoimzre

### ISSUE THREAD

**Issue by amdad** [graker/oc-photoalbums-plugin#2]
Thanks for very nice plugin.

> An exception has been thrown during the rendering of a template ("SQLSTATE[HY000]: General error: 1 no such function: RAND (SQL: select * from "graker_photoalbums_photos" order by RAND() asc limit 5)").

When using RandomPhotos Component on SQLite.

**Comment by graker** [comment]
Hi @amdad 

Yup, at the moment this component works for MySQL only. There's no DB-independent rand sorting function in Laravel 5.0. IIRC, they introduced one in 5.2.

The component code should be rewritten though so it won't throw exceptions with other DB drivers like I did [here](https://github.com/graker/blogarchive/blob/master/components/RandomPosts.php#L87). I will add this in a couple of days and post an update.

**Comment by amdad** [comment]
October will be updated to L5.5. So this will be. Thanks for reply and plugin!

**Comment by graker** [comment]
I didn't know that. Great news, thanks!

**Comment by amdad** [comment]
https://twitter.com/octobercms/status/843642213678505984

**Comment by graker** [comment]
The issue is fixed, now `RANDOM()` will be used for Sqlite, `RAND()` for MySQL and other databases would just return non-random collection.

After October updates to 5.5 I will update the component to use DB-independent function.

**Comment by amdad** [comment]
Coooool! Thanks!
