### ISSUE TITLE
Problems with selecting a photo page in Random Photo

### ISSUE THREAD

**Issue by kokomo** [graker/oc-photoalbums-plugin#9]
Is there a way to randomize photos within an album when selecting an album?

**Comment by graker** [comment]
I'm not sure what you're trying to do. Do you mean to restrict Random Photo component to a specific album? Or to randomize photos on album's page? (both things are not available though)
And what it has to do with selecting a photo page?

**Comment by kokomo** [comment]
You want to limit the Random Photo component to a specific album.
When I select an album, I want the album pictures to be displayed randomly.

**Comment by graker** [comment]
I see, thank you for elaborating.
No, there's now way to do that now. I haven't got much time at the moment, but feel free to make a PR.

**Comment by kokomo** [comment]
Using it in the current way did not produce the desired result.
So when I selected an album, I thought about how to display the album photos randomly.
Please let me know if there is a way.

**Comment by graker** [comment]
No, there's no way to do that at the moment.

**Comment by kokomo** [comment]
Thank you for your answer and attention.

**Comment by graker** [comment]
No problem.
As I said, I don't have much time to implement it now, but feel free to reopen and make a PR if you can code it yourself.
